/**
 * Script execution tools — the agent's code execution environment.
 *
 * write_script: Write a TypeScript script to ~/.dexter/scripts/
 * test_script:  Run a script in a sandboxed subprocess and verify it works
 * run_script:   Execute a script in production (after testing)
 *
 * Security model:
 * - Scripts run in a child process with a stripped environment
 * - No access to API keys or credentials (unless explicitly injected via safe allowlist)
 * - Configurable timeout (default 30s) and stdout size limit
 * - Files restricted to ~/.dexter/ output directory
 */

import { DynamicStructuredTool } from '@langchain/core/tools';
import { mkdir, writeFile, readFile, stat } from 'node:fs/promises';
import { join, resolve, isAbsolute } from 'node:path';
import { homedir } from 'node:os';
import { z } from 'zod';
import { formatToolResult } from '../types.js';
import { getScriptsDir, getCollectedDataDir } from '../../daemon/pipelines.js';

const MAX_OUTPUT_BYTES = 50_000; // 50KB max stdout
const DEFAULT_TIMEOUT_MS = 30_000;

/**
 * Environment variable allowlist for sandboxed scripts.
 *
 * EXPLICITLY EXCLUDED (never passed to scripts):
 *   OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_API_KEY — LLM credentials
 *   TELEGRAM_BOT_TOKEN — messaging credentials
 *   LANGCHAIN_API_KEY, LANGSMITH_API_KEY — observability credentials
 *   Any other secret not in this list
 *
 * Included: read-only data API keys and Dexter path configuration only.
 */
const SAFE_ENV_KEYS = [
  'HOME',
  'PATH',
  'FINANCIAL_DATASETS_API_KEY', // read-only financial data API
  'EXASEARCH_API_KEY',           // read-only web search
  'TAVILY_API_KEY',              // read-only web search fallback
  'DEXTER_SCRIPTS_DIR',
  'DEXTER_COLLECTED_DIR',
  'DEXTER_OUTPUT_DIR',
  'DEXTER_OUTPUT_PATH',          // canonical per-run output path set by pipeline runner
];

function buildSafeEnv(): Record<string, string> {
  const env: Record<string, string> = {
    DEXTER_SCRIPTS_DIR: getScriptsDir(),
    DEXTER_COLLECTED_DIR: getCollectedDataDir(),
    DEXTER_OUTPUT_DIR: join(homedir(), '.dexter', 'output'),
  };
  for (const key of SAFE_ENV_KEYS) {
    const val = process.env[key];
    if (val) env[key] = val;
  }
  return env;
}

async function runScript(
  scriptPath: string,
  timeoutMs: number = DEFAULT_TIMEOUT_MS
): Promise<{ stdout: string; stderr: string; exitCode: number; timedOut: boolean }> {
  // Ensure output directory exists
  await mkdir(join(homedir(), '.dexter', 'output'), { recursive: true });

  const proc = Bun.spawn(['bun', 'run', '--smol', scriptPath], {
    stdout: 'pipe',
    stderr: 'pipe',
    env: buildSafeEnv(),
    cwd: join(homedir(), '.dexter'),
  });

  let timedOut = false;
  const timeoutHandle = setTimeout(() => {
    timedOut = true;
    try { proc.kill(); } catch { /* already dead */ }
  }, timeoutMs);

  const [exitCode, stdoutBuf, stderrBuf] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).arrayBuffer(),
    new Response(proc.stderr).arrayBuffer(),
  ]);

  clearTimeout(timeoutHandle);

  const decoder = new TextDecoder();
  let stdout = decoder.decode(stdoutBuf);
  let stderr = decoder.decode(stderrBuf);

  // Truncate oversized output
  if (stdout.length > MAX_OUTPUT_BYTES) {
    stdout = stdout.slice(0, MAX_OUTPUT_BYTES) + '\n[output truncated]';
  }
  if (stderr.length > MAX_OUTPUT_BYTES) {
    stderr = stderr.slice(0, MAX_OUTPUT_BYTES) + '\n[stderr truncated]';
  }

  return { stdout, stderr, exitCode, timedOut };
}

// ─────────────────────────────────────────────────────────────────────────────
// write_script
// ─────────────────────────────────────────────────────────────────────────────

export const writeScriptTool = new DynamicStructuredTool({
  name: 'write_script',
  description: `Write a Bun TypeScript script to ~/.dexter/scripts/.
Use this to create data collection scripts that will be run on a schedule.
Scripts can:
  - Fetch data from financial APIs (FINANCIAL_DATASETS_API_KEY is available)
  - Write output to DEXTER_COLLECTED_DIR (available as env var)
  - Use Bun built-ins: fetch, Bun.write, Bun.file, etc.
  - Import from "node:fs/promises", "node:path", "node:os"
Scripts CANNOT: access LLM APIs, access ~/.dexter/credentials, or run subprocesses.
Always use process.env.DEXTER_COLLECTED_DIR as the output root.`,

  schema: z.object({
    filename: z.string().describe('Script filename (e.g. "AAPL-earnings-2026-Q1-collect.ts")'),
    code: z.string().describe('TypeScript code for the script'),
    description: z.string().describe('What this script does'),
  }),

  func: async ({ filename, code, description }) => {
    const dir = getScriptsDir();
    await mkdir(dir, { recursive: true });

    // Sanitize filename
    const safeName = filename.replace(/[^a-zA-Z0-9._-]/g, '-');
    const scriptPath = join(dir, safeName);

    const header = `// ${description}
// Generated by Dexter autonomous agent on ${new Date().toISOString()}
// Run: bun run ${scriptPath}
`;

    await writeFile(scriptPath, header + code, 'utf-8');

    return formatToolResult({
      scriptPath,
      filename: safeName,
      bytes: code.length,
      message: `Script written to ${scriptPath}`,
    });
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// test_script
// ─────────────────────────────────────────────────────────────────────────────

export const testScriptTool = new DynamicStructuredTool({
  name: 'test_script',
  description: `Test a previously written script by running it in a sandboxed subprocess.
Verifies the script executes without errors and produces expected output.
Always test a script before scheduling it.
Returns: stdout, stderr, exit code, and success/failure assessment.`,

  schema: z.object({
    filename: z.string().describe('Script filename (just the filename, not full path)'),
    expectedOutputPattern: z
      .string()
      .optional()
      .describe('Optional string/pattern that must appear in stdout to confirm success'),
    timeoutMs: z.number().default(30000).describe('Max execution time in milliseconds'),
  }),

  func: async ({ filename, expectedOutputPattern, timeoutMs }) => {
    const safeName = filename.replace(/[^a-zA-Z0-9._-]/g, '-');
    const scriptPath = join(getScriptsDir(), safeName);

    // Check script exists
    try {
      await stat(scriptPath);
    } catch {
      return formatToolResult({
        success: false,
        error: `Script not found: ${scriptPath}. Use write_script first.`,
      });
    }

    const result = await runScript(scriptPath, timeoutMs);

    const patternMatch =
      !expectedOutputPattern ||
      result.stdout.includes(expectedOutputPattern);

    const success =
      !result.timedOut &&
      result.exitCode === 0 &&
      patternMatch;

    return formatToolResult({
      success,
      exitCode: result.exitCode,
      timedOut: result.timedOut,
      patternMatched: patternMatch,
      stdout: result.stdout.slice(0, 3000),
      stderr: result.stderr.slice(0, 1000),
      scriptPath,
      message: success
        ? 'Script test passed — safe to schedule.'
        : `Script test FAILED: ${result.timedOut ? 'timeout' : `exit ${result.exitCode}`}. Fix before scheduling.`,
    });
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// run_script (production execution — called by pipeline runner)
// ─────────────────────────────────────────────────────────────────────────────

export const runScriptTool = new DynamicStructuredTool({
  name: 'run_script',
  description: `Execute a collection script that has already been tested.
Used by pipeline runner to collect data on schedule.
Returns the script's stdout output and any files written to DEXTER_COLLECTED_DIR.`,

  schema: z.object({
    scriptPath: z.string().describe('Full path to the script to run'),
    timeoutMs: z.number().default(60000).describe('Max execution time in ms (default 60s)'),
  }),

  func: async ({ scriptPath, timeoutMs }) => {
    const result = await runScript(scriptPath, timeoutMs);

    return formatToolResult({
      exitCode: result.exitCode,
      timedOut: result.timedOut,
      success: !result.timedOut && result.exitCode === 0,
      stdout: result.stdout,
      stderr: result.stderr.slice(0, 500),
    });
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// read_collected_data
// ─────────────────────────────────────────────────────────────────────────────

export const readCollectedDataTool = new DynamicStructuredTool({
  name: 'read_collected_data',
  description: `Read data previously collected by a pipeline script.
Use this in the processing agent to access earnings transcripts, filings, or other data.
Returns the file contents as a string.`,

  schema: z.object({
    filePath: z.string().describe('Path to the collected data file'),
  }),

  func: async ({ filePath }) => {
    // Path validation: restrict reads to the collected data directory
    const resolvedPath = resolve(isAbsolute(filePath) ? filePath : join(getCollectedDataDir(), filePath));
    const collectedDir = resolve(getCollectedDataDir());
    if (!resolvedPath.startsWith(collectedDir + '/') && resolvedPath !== collectedDir) {
      return formatToolResult({
        error: `Access denied: path must be within collected data directory (${collectedDir}). Got: ${resolvedPath}`,
      });
    }
    try {
      const content = await readFile(resolvedPath, 'utf-8');
      // Truncate very large files
      const truncated = content.length > 50000
        ? content.slice(0, 50000) + '\n[content truncated to 50KB]'
        : content;
      return formatToolResult({ content: truncated, path: resolvedPath, bytes: content.length });
    } catch (err) {
      return formatToolResult({ error: `Cannot read ${resolvedPath}: ${String(err)}` });
    }
  },
});
